# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags: ["*.*.*"]
  pull_request:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  CONFIGURATION: "Release"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet --info
    - run: git --version

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
# TBD
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Package Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nugetArtifacts
        path: |
          **/*.nupkg
          **/*.snupkg
          **/*.symbols.nupkg

  publish:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet --info
      - run: git --version

      - name: Retrieve artifacts
        uses: actions/download-artifact@v2
        with:
          name: nugetArtifacts

      - name: Publish to MyGet Packages
        run: dotnet nuget push **/*.nupkg --source ${{ vars.MYGET_SOURCE }} --api-key ${{ secrets.MYGET_TOKEN }}