# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
# TBD
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Package Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nugetArtifacts
        path: |
          **/*.nupkg
          **/*.snupkg
          **/*.symbols.nupkg

  publish:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Retrieve artifacts
        uses: actions/download-artifact@v2
        with:
          name: nugetArtifacts
      - name: Publish to GitHub Packages
        run: dotnet nuget push **/*.nupkg --source ${{ env.MYGET_SOURCE }} --api-key ${{ secrets.MYGET_TOKEN }}